name: backend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.3
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  http_parser: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.jpg
    - assets/images/signup.jpg
    - assets/images/forgetpassword.jpg
    - assets/images/google_logo.png
    - assets/images/main.jpg
    - assets/images/new1.jfif
    - assets/images/new2.jfif
    - assets/images/new3.jfif 
    - assets/images/sale1.jfif
    - assets/images/sale2.jfif
    - assets/images/sale3.jfif
    - assets/images/sale4.jfif
    - assets/images/anhchu.png 
    - assets/images/anhchu1.jpg
    - assets/images/anhchu2.jpg
    - assets/images/anhchu2_1.jpg
    - assets/images/anhchu2_2.jpg
    - assets/images/new_categorie.jfif
    - assets/images/cloth_categories.jpg
    - assets/images/shoes_categories.jpg
    - assets/images/accscories_categories.jpg